In [98]:
import pandas as pd
import re

In [72]:
# Read data from csv file
dataframe = pd.read_csv('data/combined_csv.csv')

In [73]:
# Change price unit into billion
val_price = dataframe['price'].values.tolist()
val_area = dataframe['Diện tích'].values.tolist()
for i in range(len(val_area)):
    if isinstance(val_area[i], str):
        val_area[i] = float(val_area[i].replace('m2', ''))
for i in range(len(val_price)):
    if isinstance(val_price[i], str):
        if 'tỷ VNĐ/m2' in val_price[i]:
                val_price[i] = int(float(val_price[i].replace('tỷ VNĐ/m2', '').replace(',', '.'))*val_area[i]* 10e3)
        elif 'tỷ VNĐ' in val_price[i]:
                val_price[i] = int(float(val_price[i].replace('tỷ VNĐ', '').replace(',', '.'))* 10e3)
        elif 'triệu VNĐ/m2' in val_price[i]:
                val_price[i] = int(float(val_price[i].replace('triệu VNĐ/m2', '').replace(',', '.'))*val_area[i])
        elif 'triệu VNĐ' in val_price[i]:
                val_price[i] = int(float(val_price[i].replace('triệu VNĐ', '').replace(',', '.')))
dataframe['price']=val_price
dataframe['Diện tích']=val_area

In [74]:
# Drop nan in numerical attributes
dataframe = dataframe[dataframe['price'].notna()]
dataframe = dataframe[dataframe['Diện tích'].notna()]
dataframe = dataframe[dataframe['Mặt tiền'].notna()]
dataframe = dataframe[dataframe['Lộ giới'].notna()]

In [75]:
dataframe.tail()

,price,address,Diện tích,Mặt tiền,Lộ giới,Số tầng,Số phòng ngủ,Ngày đăng,Loại tin,id,Số toilet,Hướng
11778,245000,"Đường Linh Đàm, Đại Kim, Hoàng Mai",224.0,15.0,13.0,4.0,8.0,05/12/2022,Tin thường,batdongsan_so_com_vn_1670440674.5257807,5.0,NaN
11780,78900,"Đường Nguyễn Khang, Yên Hòa, Cầu Giấy",48.0,6.0,5.0,6.0,4.0,05/12/2022,Tin thường,batdongsan_so_com_vn_1670440679.7092428,5.0,NaN
11781,28000,"Đường Tỉnh Lộ 422B, Vân Canh, Hoài Đức",40.0,7.0,3.0,4.0,4.0,05/12/2022,Tin thường,batdongsan_so_com_vn_1670440682.1170754,3.0,NaN
11782,110000,"Đường Hào Nam, Ô Chợ Dừa, Đống Đa",55.0,4.0,4.0,4.0,3.0,05/12/2022,Tin thường,batdongsan_so_com_vn_1670440684.117509,4.0,NaN
11783,15600,"Đường 1, Ngọc Thụy, Long Biên",62.0,38.0,3.0,2.0,2.0,05/12/2022,Tin thường,batdongsan_so_com_vn_1670440686.7075593,2.0,NaN

In [86]:
dataframe['Số phòng ngủ'] = dataframe['Số phòng ngủ'].fillna('None')
dataframe['Số tầng'] = dataframe['Số tầng'].fillna('None')
dataframe['Số toilet'] = dataframe['Số toilet'].fillna('None')

val_bedrooms = dataframe['Số phòng ngủ'].values.tolist()
val_floors = dataframe['Số tầng'].values.tolist()
val_toilets = dataframe['Số toilet'].values.tolist()
for i in range(len(val_bedrooms)):
    if val_bedrooms[i] != 'None':
        val_bedrooms[i] = str(int(val_bedrooms[i]))
for i in range(len(val_floors)):
    if val_floors[i] != 'None':
        val_floors[i] = str(int(val_floors[i]))
for i in range(len(val_toilets)):
    if val_toilets[i] != 'None':
        val_toilets[i] = str(int(val_toilets[i]))
    
dataframe['Số phòng ngủ']=val_bedrooms
dataframe['Số tầng']=val_floors
dataframe['Số toilet']=val_toilets

In [113]:
# Rename Attributes
dataframe = dataframe.rename(columns={'price': 'Price', 'Diện tích': 'Area', 'Mặt tiền': 'Facade', 'Lộ giới': 'Building Line', 'Số tầng': 'Floors', 'Số phòng ngủ': 'Bedrooms','Ngày đăng': 'Publish Time', 'Số toilet': 'Toilets', 'Hướng': 'Direction', 'Loại tin': 'Type', 'price': 'Price', 'id': 'ID', 'address': 'Address'})

In [114]:
dataframe.tail()

,Price,Address,Area,Facade,Building Line,Floors,Bedrooms,Pulish Time,Type,ID,Toilets,Direction,District
11778,245000,"Đường Linh Đàm, Đại Kim, Hoàng Mai",224.0,15.0,13.0,4,8,05/12/2022,Tin thường,batdongsan_so_com_vn_1670440674.5257807,5,NaN,Hoàng Mai
11780,78900,"Đường Nguyễn Khang, Yên Hòa, Cầu Giấy",48.0,6.0,5.0,6,4,05/12/2022,Tin thường,batdongsan_so_com_vn_1670440679.7092428,5,NaN,Cầu Giấy
11781,28000,"Đường Tỉnh Lộ 422B, Vân Canh, Hoài Đức",40.0,7.0,3.0,4,4,05/12/2022,Tin thường,batdongsan_so_com_vn_1670440682.1170754,3,NaN,Hoài Đức
11782,110000,"Đường Hào Nam, Ô Chợ Dừa, Đống Đa",55.0,4.0,4.0,4,3,05/12/2022,Tin thường,batdongsan_so_com_vn_1670440684.117509,4,NaN,Đống Đa
11783,15600,"Đường 1, Ngọc Thụy, Long Biên",62.0,38.0,3.0,2,2,05/12/2022,Tin thường,batdongsan_so_com_vn_1670440686.7075593,2,NaN,Long Biên

In [111]:
# Address Handling
Hanoi_districts = ['Hoàn Kiếm', 'Đống Đa', 'Ba Đình', 'Hai Bà Trưng', 'Hoàng Mai', 'Thanh Xuân', 'Long Biên', 'Nam Từ Liêm', 'Bắc Từ Liêm', 'Tây Hồ', 'Cầu Giấy', 'Hà Đông', 'Sơn Tây', 'Ba Vì', 'Chương Mỹ', 'Phúc Thọ', 'Đan Phượng', 'Đông Anh', 'Gia Lâm', 'Hoài Đức', 'Mê Linh', 'Mỹ Đức', 'Phú Xuyên', 'Quốc Oai', 'Sóc Sơn', 'Thạch Thất', 'Thanh Oai', 'Thường Tín', 'Ứng Hòa', 'Thanh Trì']

dataframe['Address'] = dataframe['Address'].fillna('None')
val_address = dataframe['Address'].values.tolist()
data_district = []
for i in range(len(val_bedrooms)):
    if val_bedrooms[i] != None:
        res = re.findall(r'\w+', val_address[i])
        if len(res) >= 2:
            district = [res[-2:][0] + ' '+ res[-2:][1]]
            if district[0] in Hanoi_districts:
                data_district.append(district[0])
            else:
                if len(res) >= 3:
                    district_three_words  = [res[-3:][0] + ' '+ res[-3:][1] + ' '+ res[-3:][2]]
                    if district_three_words[0] in Hanoi_districts:
                        data_district.append(district_three_words[0])
                    else:
                        data_district.append('None')
                else:
                    data_district.append('None')
        else:
            data_district.append('None')
dataframe['District'] = data_district

In [121]:
dataframe.drop(['Address'], axis=1)

KeyError: "['Address'] not found in axis"

In [123]:
dataframe.to_csv('combined_csv.csv')